# Execute with "./Variables.ps1" to restore previously-saved variables.
Set-Variable -Scope Global -Name ACA_ENVIRONMENT_SUBNET_ID -Value /subscriptions/5fb73327-9152-4f64-bf8a-90dc0cc4ad8f/resourceGroups/rg-tasks-tracker-3fpetx/providers/Microsoft.Network/virtualNetworks/vnet-tasks-tracker/subnets/ContainerAppSubnet
Set-Variable -Scope Global -Name API_APP_PORT -Value 7152
Set-Variable -Scope Global -Name APPINSIGHTS_NAME -Value appi-tasks-tracker-3fpetx
Set-Variable -Scope Global -Name APPINSIGHTS_INSTRUMENTATIONKEY -Value 255a391c-33ad-4465-ab23-3dc92afe4239
Set-Variable -Scope Global -Name AZURE_CONTAINER_REGISTRY_NAME -Value crtaskstracker3fpetx
Set-Variable -Scope Global -Name AZURE_SUBSCRIPTION_ID -Value 5fb73327-9152-4f64-bf8a-90dc0cc4ad8f
Set-Variable -Scope Global -Name BACKEND_API_EXTERNAL_BASE_URL -Value https://tasksmanager-backend-api.livelypebble-1933abe8.eastus.azurecontainerapps.io
Set-Variable -Scope Global -Name BACKEND_API_INTERNAL_BASE_URL -Value https://tasksmanager-backend-api.internal.livelypebble-1933abe8.eastus.azurecontainerapps.io
Set-Variable -Scope Global -Name BACKEND_API_NAME -Value tasksmanager-backend-api
Set-Variable -Scope Global -Name BACKEND_API_PRINCIPAL_ID -Value 4da0c06e-f7e8-496b-8ba5-441fefbb7220
Set-Variable -Scope Global -Name BACKEND_SERVICE_APP_PORT -Value 7297
Set-Variable -Scope Global -Name BACKEND_SERVICE_NAME -Value tasksmanager-backend-processor
Set-Variable -Scope Global -Name BACKEND_SERVICE_PRINCIPAL_ID -Value d2c7c3af-00cc-4e7f-893c-cc877852c74c
Set-Variable -Scope Global -Name COSMOS_DB_ACCOUNT -Value cosmos-tasks-tracker-state-store-3fpetx
Set-Variable -Scope Global -Name COSMOS_DB_CONTAINER -Value taskscollection
Set-Variable -Scope Global -Name COSMOS_DB_DBNAME -Value tasksmanagerdb
Set-Variable -Scope Global -Name COSMOS_DB_ENDPOINT -Value https://cosmos-tasks-tracker-state-store-3fpetx.documents.azure.com:443/
Set-Variable -Scope Global -Name COSMOS_DB_PRIMARY_MASTER_KEY -Value mAokBwj9A6ODB6H520PzfW4S3qmZ2bDbLTOz1CI19UlpyZxOTrH2MUd1innHpa8An71lIQwfXRygACDbZXr9Ag==
Set-Variable -Scope Global -Name ENVIRONMENT -Value cae-tasks-tracker
Set-Variable -Scope Global -Name FRONTEND_UI_BASE_URL -Value https://tasksmanager-frontend-webapp.livelypebble-1933abe8.eastus.azurecontainerapps.io
Set-Variable -Scope Global -Name FRONTEND_UI_BASE_URL_LOCAL -Value https://localhost:7108
Set-Variable -Scope Global -Name FRONTEND_WEBAPP_NAME -Value tasksmanager-frontend-webapp
Set-Variable -Scope Global -Name KEYVAULT_NAME -Value kv-tasks-tracker-3fpetx
Set-Variable -Scope Global -Name KEYVAULT_SECRETS_OFFICER_ROLE_ID -Value b86a8fe4-44ce-4948-aee5-eccb2c155cd7
Set-Variable -Scope Global -Name KEYVAULT_SECRETS_USER_ROLE_ID -Value 4633458b-17de-408a-b874-0445c86b69e6
Set-Variable -Scope Global -Name LOCATION -Value eastus
Set-Variable -Scope Global -Name RANDOM_STRING -Value 3fpetx
Set-Variable -Scope Global -Name RESOURCE_GROUP -Value rg-tasks-tracker-3fpetx
Set-Variable -Scope Global -Name REVISION_NAME -Value tasksmanager-backend-api--v-2
Set-Variable -Scope Global -Name ROLE_ID -Value 00000000-0000-0000-0000-000000000002
Set-Variable -Scope Global -Name SERVICE_BUS_CONNECTION_STRING -Value Endpoint=sb://sbns-taskstracker-3fpetx.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=UpvDNx/3uk3q2a7Q5iRFiJEnV2C7o3uu3+ASbMzRz78=
Set-Variable -Scope Global -Name SERVICE_BUS_NAMESPACE_NAME -Value sbns-taskstracker-3fpetx
Set-Variable -Scope Global -Name SERVICE_BUS_TOPIC_NAME -Value tasksavedtopic
Set-Variable -Scope Global -Name SERVICE_BUS_TOPIC_SUBSCRIPTION -Value sbts-tasks-processor
Set-Variable -Scope Global -Name SIGNEDIN_USERID -Value 744cffd5-e99d-4cc0-9fe3-2d284e07a1c4
Set-Variable -Scope Global -Name STORAGE_ACCOUNT_NAME -Value sttaskstracker3fpetx
Set-Variable -Scope Global -Name STORAGE_ACCOUNT_KEY -Value mrtTwIrwv8bfKzCkF4I4Ib0r2TQTQbUCaix6bWv7Y1cMD00SROyPR22+8pWPW0V2g6N2u/NRht/Q+AStERMYKg==
Set-Variable -Scope Global -Name TARGET_PORT -Value 5000
Set-Variable -Scope Global -Name UI_APP_PORT -Value 7108
Set-Variable -Scope Global -Name VNET_NAME -Value vnet-tasks-tracker
Set-Variable -Scope Global -Name WORKSPACE_ID -Value cd80fcd8-4582-4db8-b444-4898a8f4255d
Set-Variable -Scope Global -Name WORKSPACE_NAME -Value log-tasks-tracker-3fpetx
Set-Variable -Scope Global -Name WORKSPACE_SECRET -Value 6mLVOgmLkkAfHxW++LmnIItUrSGmGIQcltphnwFcud+3d57phlV7e3wYxZ7IaZKgciP73i+5nAxrrzrNQ/EOEw==
Set-Variable -Scope Global -Name TODAY -Value (Get-Date -Format 'yyyyMMdd')
Write-Host "Set 44 variables."
