apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: externaltasksmanager
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
    - name: storageAccount
      value: "sttaskstracker3fpetx"
    - name: storageAccessKey
      value: "mrtTwIrwv8bfKzCkF4I4Ib0r2TQTQbUCaix6bWv7Y1cMD00SROyPR22+8pWPW0V2g6N2u/NRht/Q+AStERMYKg=="
    - name: queue
      value: "external-tasks-queue"
    - name: decodeBase64
      value: "true"
    - name: route
      value: /externaltasksprocessor/process